### PR TITLE
prevent idb connection from closing to allow for SQL queries using the IDB SQLite Database tool

### LINKED ISSUE #273: Compiled kindling from source idb sql query issue
I am having this issue where when running any sql query on `system_logs.idb` does not work and returns `database connection closed` error.

Image

when using this on `metrics.idb` this works though. 

Image

### Java Version
PS C:\Users\Spencer41965\Documents\code\work\java\kindling> java --version
openjdk 21.0.7 2025-04-15 LTS
OpenJDK Runtime Environment Microsoft-11369940 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Microsoft-11369940 (build 21.0.7+6-LTS, mixed mode, sharing)
PS C:\Users\Spencer41965\Documents\code\work\java\kindling>

### Gradle run execution

3:59:13 PM: Executing 'run'…

> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

> Configure project :
warning: Dokka Gradle plugin V1 is deprecated
    
    Dokka Gradle plugin V1 is deprecated, and will be removed in Dokka version 2.1.0
    Please migrate to Dokka Gradle plugin V2. This will require updating your project.
    To learn about migrating read the migration guide https://kotl.in/dokka-gradle-migration
    
    To start migrating to Dokka Gradle plugin V2 add
        org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
    into your project's `gradle.properties` file.
    
    We would appreciate your feedback!
     - Please report any feedback or problems https://kotl.in/dokka-issues
     - Chat with the community visit #dokka in https://kotlinlang.slack.com/ (To sign up visit https://kotl.in/slack)
    

> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :compileKotlin FROM-CACHE
> Task :compileJava FROM-CACHE
> Task :download79 UP-TO-DATE
> Task :download80 UP-TO-DATE
> Task :download81 UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :run
WARNING: package apple.laf not in java.desktop
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@19e1023e]
SLF4J(W): Found provider [org.slf4j.reload4j.Reload4jServiceProvider@7cef4e59]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@19e1023e]

### PR DESCRIPTION
**Pull request by SpencerLommel**
This PR suggests a fix for https://github.com/inductiveautomation/kindling/issues/273

Previously, when you attempted to use the sql query tool on a system_logs.idb file. It would error out because the idb file connection is closed after being loaded in.

This small patch just prevents this from being closed so we can use the sql query tool.

This shouldn't have any unintended affects as idb files (for now) are read only so we don't really need to worry about corruption

Fixes #273

### CODE REVIEW

**Comment by SpencerLommel** [comment]
This PR also addresses a fix to https://github.com/inductiveautomation/kindling/issues/275 by converting our timestmp Long to a Date that can be used by our table. 

I used the same date formatting ("2025-06-13 15:30:08:373") that is already used in the Logs tab to maintain consistency.


Going forward, would you prefer if I open separate PR's for each issue or could I combine them into one like I did here for similar issues?

File: src/main/kotlin/io/github/inductiveautomation/kindling/idb/generic/QueryResult.kt [hunk 1]
```diff
@@ -18,7 +19,13 @@ sealed interface QueryResult {
         override fun getColumnCount(): Int = columnNames.size
         override fun getColumnName(columnIndex: Int): String = columnNames[columnIndex]
         override fun getColumnClass(columnIndex: Int): Class<*> = columnTypes[columnIndex]
-        override fun getValueAt(rowIndex: Int, columnIndex: Int): Any? = data[rowIndex][columnIndex]
+        override fun getValueAt(rowIndex: Int, columnIndex: Int): Any? {
+            val row = data[rowIndex]
+            return when (columnIndex) {
+                0 -> Date(row[0] as Long) // "timestmp" column, convert Long to Date
```
Comment (paul-griffith) [inline src/main/kotlin/io/github/inductiveautomation/kindling/idb/generic/QueryResult.kt:25]: I liked your first fix in https://github.com/paul-griffith/kindling/pull/174 better 😄 
This will only work if the first column happens to be a timestamp-as-long, right? (plus it'll blow up if the first column is any other data type). I think there's definitely something to do better here, but it might have to involve adjusting the data during `QueryResult` construction, where the `Timestamp` type columns are coming from.

**Review by paul-griffith — CHANGES_REQUESTED** [review]
In general one-PR-per-issue is nicer to work with as a reviewer, but I'm guilty of doing the same thing myself so it's not a very big deal - especially with small stuff like this. Yesterday I did some work to clean up how these IDB tabs are created in the first place (and address this issue) that I'll put up soon, though, so you may want to hold off or we'll end up with merge conflicts.

**Comment by SpencerLommel** [comment]
> In general one-PR-per-issue is nicer to work with as a reviewer, but I'm guilty of doing the same thing myself so it's not a very big deal - especially with small stuff like this. Yesterday I did some work to clean up how these IDB tabs are created in the first place (and address this issue) that I'll put up soon, though, so you may want to hold off or we'll end up with merge conflicts.

I rolled back my second commit and now it's just the single one that fixes closing the connection early

**Review by paul-griffith — APPROVED** [review]
